update-beauty: perform clang-format on sources

diff --git a/remote/update-beauty b/remote/update-beauty
--- a/remote/update-beauty
+++ b/remote/update-beauty
@@ -32,6 +32,12 @@
 #   By default: false
 # hooks.gofmtoptions
 #   Options given to go fmt
+# hooks.clangformat
+#   Perform clang-format validation on C/C++(...) code
+#   By default: false (set it to binary name)
+# hooks.clangformatoptions
+#   Options for clang-format (not config)
+#   Example: "{ TabWidth: 4, Language: Cpp }"
 # hooks.verbose
 #   Some useful information for debugging
 #   By default: false
@@ -67,13 +73,20 @@ numberofcharsperline=$(git config --int hooks.numberofcharsperline)
 regexpforcommittitle=$(git config hooks.regexpforcommittitle)
 invertregexpforpatchnewchanges=$(git config hooks.invertregexpforpatchnewchanges)
 beatymergecommits=$(git config --bool hooks.beatymergecommits)
+
 gofmt=$(git config --bool hooks.gofmt)
 gofmtoptionstemp=$(git config hooks.gofmtoptions)
 gofmtoptions=${gofmtoptionstemp:-"-s=true"}
 
+clangformat=$(git config hooks.clangformat)
+clangformatoptions=$(git config hooks.clangformatoptions)
+
 # Initialize some default values
 if [[ $numberofcharsperline -eq 0 ]]; then
     numberofcharsperline=80
+fi
+if [ -n "$clangformatoptions" ]; then
+    clangformatoptions="-style=\"$clangformatoptions\""
 fi
 
 zero="0000000000000000000000000000000000000000"
@@ -148,8 +161,21 @@ validate_ref()
         files=$(git diff --name-only $ref^..$ref | grep .*.go )
         for f in $files; do
             fmt=$(git cat-file -p $ref:$f | gofmt $gofmtoptions -d=true 2>&1)
-            if [ ! -z "$fmt" ]; then
+            if [ -n "$fmt" ]; then
                 echo "*** Error you need to perform gofmt on $f <$ref>"
+                debug_message "$fmt"
+                exit 1
+            fi
+        done
+    fi
+
+    # hooks.clangformat
+    if [ -n "$clangformat" ]; then
+        files=$(git diff --name-only $ref^..$ref | egrep "\.(cpp|cc|c|h|hpp|cxx)$")
+        for f in $files; do
+            fmt=$(diff -u <(git cat-file -p $ref:$f) <(git cat-file -p $ref:$f | eval $clangformat $clangformatoptions))
+            if [ -n "$fmt" ]; then
+                echo "*** Error you need to perform clang-format on $f <$ref>"
                 debug_message "$fmt"
                 exit 1
             fi
